@startuml

class BrainLord { 
	NUM_ROUNDS
	play()
	FeedBack checkGuess(Pattern) 
} 

class Player {
	Pattern guess() 
	giveFeedBack(FeedBack) 
	win() 
	lose() 
} 

class Pattern { 
	validChars
	generate() 
	FeedBack check(Pattern) 
	show() 
} 

class FeedBack { 
	bool isVictory() 
	show() 
} 



BrainLord *-- Player 
BrainLord *-- Pattern 
BrainLord ..> FeedBack 

Player ..> Pattern 
Player ..> FeedBack 

Pattern ..> FeedBack

@enduml