@startuml

class BrainLord { 
	NUM_ROUNDS
	play()
	FeedBack checkGuess(Pattern) 
} 

class Player {
	Pattern guess() 
	giveFeedBack(FeedBack) 
	win() 
	lose() 
} 

class Pattern { 
	validColors
	generate() 
	FeedBack check(Pattern) 
	show() 
} 

class FeedBack { 
	bool isVictory() 
	show() 
} 

class Row {
	LENGTH
}

BrainLord *-- Player 
BrainLord *-- Pattern 
BrainLord ..> FeedBack 

Player ..> Pattern 
Player ..> FeedBack
Player ..> Row

Pattern *-- Row
FeedBack *-- Row

@enduml